export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_INVALID_RESET_TOKEN: 'AUTH_INVALID_RESET_TOKEN',
  AUTH_PASSWORD_RESET_UNAVAILABLE: 'AUTH_PASSWORD_RESET_UNAVAILABLE',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ID_ALREADY_EXISTS: 'USER_ID_ALREADY_EXISTS',
  USER_ID_CHANGE_TOO_FREQUENT: 'USER_ID_CHANGE_TOO_FREQUENT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_ID_ALREADY_EXISTS: 'GROUP_ID_ALREADY_EXISTS',
  GROUP_FULL: 'GROUP_FULL',
  GROUP_DISSOLVED: 'GROUP_DISSOLVED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  MESSAGE_TOO_FAST: 'MESSAGE_TOO_FAST',
  GROUP_RATE_LIMITED: 'GROUP_RATE_LIMITED',
  MESSAGE_TYPE_NOT_ALLOWED: 'MESSAGE_TYPE_NOT_ALLOWED',
  USER_BLOCKED: 'USER_BLOCKED',
  NOT_FRIENDS: 'NOT_FRIENDS',
  FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
  FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  MESSAGE_EXPIRED: 'MESSAGE_EXPIRED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  QUOTED_MESSAGE_NOT_FOUND: 'QUOTED_MESSAGE_NOT_FOUND',
  LINK_PREVIEW_FAILED: 'LINK_PREVIEW_FAILED',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  OWNER_MUST_TRANSFER: 'OWNER_MUST_TRANSFER',
  CANNOT_KICK_ADMIN: 'CANNOT_KICK_ADMIN',
  CANNOT_KICK_OWNER: 'CANNOT_KICK_OWNER',
  MAX_MEMBERS_TOO_LOW: 'MAX_MEMBERS_TOO_LOW',
  MAX_MEMBERS_TOO_HIGH: 'MAX_MEMBERS_TOO_HIGH',
  SIGNUP_DISABLED: 'SIGNUP_DISABLED',
  STRANGER_DM_DENIED: 'STRANGER_DM_DENIED',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  ANNOUNCEMENT_NOT_FOUND: 'ANNOUNCEMENT_NOT_FOUND',
  MOMENT_NOT_FOUND: 'MOMENT_NOT_FOUND',
  MOMENT_NOT_VISIBLE: 'MOMENT_NOT_VISIBLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export type ApiSuccess<T> = { ok: true; data: T };
export type ApiFailure = {
  ok: false;
  error: { code: ErrorCode | string; message: string; details?: unknown; retry_after_ms?: number };
};
export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;
